services:
  pg:
    image: postgres:latest
    container_name: pg-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-dynamic-selection}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4:8.9
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '7777:80'
    volumes:
      - pgadmin_local:/var/lib/pgadmin
    depends_on:
      - pg
    restart: always

  dynamic-ad-set-api:
    container_name: dynamic-ad-set-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    volumes:
      - ./:/usr/src/dynamic-ad-set-api
    depends_on:
      - pg
    command: sh -c "npm install && npm run migration:run && npm start"

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/var/lib/redis
    ports:
      - ${REDIS_PORT-6379}:6379
    restart: always

volumes:
  postgres_data:
  pgadmin_local:
  redis:
